/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing Amount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AmountTests
    {
        // TODO uncomment below to declare an instance variable for Amount
        //private Amount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Amount
            //instance = new Amount();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Amount
        /// </summary>
        [Test]
        public void AmountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Amount
            //Assert.IsInstanceOfType<Amount> (instance, "variable 'instance' is a Amount");
        }


        /// <summary>
        /// Test the property 'ConvertedFromCurrency'
        /// </summary>
        [Test]
        public void ConvertedFromCurrencyTest()
        {
            // TODO unit test for the property 'ConvertedFromCurrency'
        }
        /// <summary>
        /// Test the property 'ConvertedFromValue'
        /// </summary>
        [Test]
        public void ConvertedFromValueTest()
        {
            // TODO unit test for the property 'ConvertedFromValue'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
