/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing Buyer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BuyerTests
    {
        // TODO uncomment below to declare an instance variable for Buyer
        //private Buyer instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Buyer
            //instance = new Buyer();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Buyer
        /// </summary>
        [Test]
        public void BuyerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Buyer
            //Assert.IsInstanceOfType<Buyer> (instance, "variable 'instance' is a Buyer");
        }


        /// <summary>
        /// Test the property 'BuyerRegistrationAddress'
        /// </summary>
        [Test]
        public void BuyerRegistrationAddressTest()
        {
            // TODO unit test for the property 'BuyerRegistrationAddress'
        }
        /// <summary>
        /// Test the property 'TaxAddress'
        /// </summary>
        [Test]
        public void TaxAddressTest()
        {
            // TODO unit test for the property 'TaxAddress'
        }
        /// <summary>
        /// Test the property 'TaxIdentifier'
        /// </summary>
        [Test]
        public void TaxIdentifierTest()
        {
            // TODO unit test for the property 'TaxIdentifier'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

    }

}
