/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing CancelRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CancelRequestTests
    {
        // TODO uncomment below to declare an instance variable for CancelRequest
        //private CancelRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CancelRequest
            //instance = new CancelRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CancelRequest
        /// </summary>
        [Test]
        public void CancelRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CancelRequest
            //Assert.IsInstanceOfType<CancelRequest> (instance, "variable 'instance' is a CancelRequest");
        }


        /// <summary>
        /// Test the property 'CancelCompletedDate'
        /// </summary>
        [Test]
        public void CancelCompletedDateTest()
        {
            // TODO unit test for the property 'CancelCompletedDate'
        }
        /// <summary>
        /// Test the property 'CancelInitiator'
        /// </summary>
        [Test]
        public void CancelInitiatorTest()
        {
            // TODO unit test for the property 'CancelInitiator'
        }
        /// <summary>
        /// Test the property 'CancelReason'
        /// </summary>
        [Test]
        public void CancelReasonTest()
        {
            // TODO unit test for the property 'CancelReason'
        }
        /// <summary>
        /// Test the property 'CancelRequestedDate'
        /// </summary>
        [Test]
        public void CancelRequestedDateTest()
        {
            // TODO unit test for the property 'CancelRequestedDate'
        }
        /// <summary>
        /// Test the property 'CancelRequestId'
        /// </summary>
        [Test]
        public void CancelRequestIdTest()
        {
            // TODO unit test for the property 'CancelRequestId'
        }
        /// <summary>
        /// Test the property 'CancelRequestState'
        /// </summary>
        [Test]
        public void CancelRequestStateTest()
        {
            // TODO unit test for the property 'CancelRequestState'
        }

    }

}
