/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing EbayVaultProgram
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EbayVaultProgramTests
    {
        // TODO uncomment below to declare an instance variable for EbayVaultProgram
        //private EbayVaultProgram instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EbayVaultProgram
            //instance = new EbayVaultProgram();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EbayVaultProgram
        /// </summary>
        [Test]
        public void EbayVaultProgramInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EbayVaultProgram
            //Assert.IsInstanceOfType<EbayVaultProgram> (instance, "variable 'instance' is a EbayVaultProgram");
        }


        /// <summary>
        /// Test the property 'FulfillmentType'
        /// </summary>
        [Test]
        public void FulfillmentTypeTest()
        {
            // TODO unit test for the property 'FulfillmentType'
        }

    }

}
