/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing ExtendedContact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtendedContactTests
    {
        // TODO uncomment below to declare an instance variable for ExtendedContact
        //private ExtendedContact instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExtendedContact
            //instance = new ExtendedContact();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExtendedContact
        /// </summary>
        [Test]
        public void ExtendedContactInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExtendedContact
            //Assert.IsInstanceOfType<ExtendedContact> (instance, "variable 'instance' is a ExtendedContact");
        }


        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'ContactAddress'
        /// </summary>
        [Test]
        public void ContactAddressTest()
        {
            // TODO unit test for the property 'ContactAddress'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Test]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'PrimaryPhone'
        /// </summary>
        [Test]
        public void PrimaryPhoneTest()
        {
            // TODO unit test for the property 'PrimaryPhone'
        }

    }

}
