/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing FileInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FileInfoTests
    {
        // TODO uncomment below to declare an instance variable for FileInfo
        //private FileInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FileInfo
            //instance = new FileInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FileInfo
        /// </summary>
        [Test]
        public void FileInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FileInfo
            //Assert.IsInstanceOfType<FileInfo> (instance, "variable 'instance' is a FileInfo");
        }


        /// <summary>
        /// Test the property 'FileId'
        /// </summary>
        [Test]
        public void FileIdTest()
        {
            // TODO unit test for the property 'FileId'
        }
        /// <summary>
        /// Test the property 'FileType'
        /// </summary>
        [Test]
        public void FileTypeTest()
        {
            // TODO unit test for the property 'FileType'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'UploadedDate'
        /// </summary>
        [Test]
        public void UploadedDateTest()
        {
            // TODO unit test for the property 'UploadedDate'
        }

    }

}
