/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing FileEvidence
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FileEvidenceTests
    {
        // TODO uncomment below to declare an instance variable for FileEvidence
        //private FileEvidence instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FileEvidence
            //instance = new FileEvidence();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FileEvidence
        /// </summary>
        [Test]
        public void FileEvidenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FileEvidence
            //Assert.IsInstanceOfType<FileEvidence> (instance, "variable 'instance' is a FileEvidence");
        }


        /// <summary>
        /// Test the property 'FileId'
        /// </summary>
        [Test]
        public void FileIdTest()
        {
            // TODO unit test for the property 'FileId'
        }

    }

}
