/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing InfoFromBuyer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InfoFromBuyerTests
    {
        // TODO uncomment below to declare an instance variable for InfoFromBuyer
        //private InfoFromBuyer instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InfoFromBuyer
            //instance = new InfoFromBuyer();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InfoFromBuyer
        /// </summary>
        [Test]
        public void InfoFromBuyerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InfoFromBuyer
            //Assert.IsInstanceOfType<InfoFromBuyer> (instance, "variable 'instance' is a InfoFromBuyer");
        }


        /// <summary>
        /// Test the property 'ContentOnHold'
        /// </summary>
        [Test]
        public void ContentOnHoldTest()
        {
            // TODO unit test for the property 'ContentOnHold'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'ReturnShipmentTracking'
        /// </summary>
        [Test]
        public void ReturnShipmentTrackingTest()
        {
            // TODO unit test for the property 'ReturnShipmentTracking'
        }

    }

}
