/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing Order
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderTests
    {
        // TODO uncomment below to declare an instance variable for Order
        //private Order instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Order
            //instance = new Order();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Order
        /// </summary>
        [Test]
        public void OrderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Order
            //Assert.IsInstanceOfType<Order> (instance, "variable 'instance' is a Order");
        }


        /// <summary>
        /// Test the property 'Buyer'
        /// </summary>
        [Test]
        public void BuyerTest()
        {
            // TODO unit test for the property 'Buyer'
        }
        /// <summary>
        /// Test the property 'BuyerCheckoutNotes'
        /// </summary>
        [Test]
        public void BuyerCheckoutNotesTest()
        {
            // TODO unit test for the property 'BuyerCheckoutNotes'
        }
        /// <summary>
        /// Test the property 'CancelStatus'
        /// </summary>
        [Test]
        public void CancelStatusTest()
        {
            // TODO unit test for the property 'CancelStatus'
        }
        /// <summary>
        /// Test the property 'CreationDate'
        /// </summary>
        [Test]
        public void CreationDateTest()
        {
            // TODO unit test for the property 'CreationDate'
        }
        /// <summary>
        /// Test the property 'EbayCollectAndRemitTax'
        /// </summary>
        [Test]
        public void EbayCollectAndRemitTaxTest()
        {
            // TODO unit test for the property 'EbayCollectAndRemitTax'
        }
        /// <summary>
        /// Test the property 'FulfillmentHrefs'
        /// </summary>
        [Test]
        public void FulfillmentHrefsTest()
        {
            // TODO unit test for the property 'FulfillmentHrefs'
        }
        /// <summary>
        /// Test the property 'FulfillmentStartInstructions'
        /// </summary>
        [Test]
        public void FulfillmentStartInstructionsTest()
        {
            // TODO unit test for the property 'FulfillmentStartInstructions'
        }
        /// <summary>
        /// Test the property 'LastModifiedDate'
        /// </summary>
        [Test]
        public void LastModifiedDateTest()
        {
            // TODO unit test for the property 'LastModifiedDate'
        }
        /// <summary>
        /// Test the property 'LegacyOrderId'
        /// </summary>
        [Test]
        public void LegacyOrderIdTest()
        {
            // TODO unit test for the property 'LegacyOrderId'
        }
        /// <summary>
        /// Test the property 'LineItems'
        /// </summary>
        [Test]
        public void LineItemsTest()
        {
            // TODO unit test for the property 'LineItems'
        }
        /// <summary>
        /// Test the property 'OrderFulfillmentStatus'
        /// </summary>
        [Test]
        public void OrderFulfillmentStatusTest()
        {
            // TODO unit test for the property 'OrderFulfillmentStatus'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'OrderPaymentStatus'
        /// </summary>
        [Test]
        public void OrderPaymentStatusTest()
        {
            // TODO unit test for the property 'OrderPaymentStatus'
        }
        /// <summary>
        /// Test the property 'PaymentSummary'
        /// </summary>
        [Test]
        public void PaymentSummaryTest()
        {
            // TODO unit test for the property 'PaymentSummary'
        }
        /// <summary>
        /// Test the property 'PricingSummary'
        /// </summary>
        [Test]
        public void PricingSummaryTest()
        {
            // TODO unit test for the property 'PricingSummary'
        }
        /// <summary>
        /// Test the property 'Program'
        /// </summary>
        [Test]
        public void ProgramTest()
        {
            // TODO unit test for the property 'Program'
        }
        /// <summary>
        /// Test the property 'SalesRecordReference'
        /// </summary>
        [Test]
        public void SalesRecordReferenceTest()
        {
            // TODO unit test for the property 'SalesRecordReference'
        }
        /// <summary>
        /// Test the property 'SellerId'
        /// </summary>
        [Test]
        public void SellerIdTest()
        {
            // TODO unit test for the property 'SellerId'
        }
        /// <summary>
        /// Test the property 'TotalFeeBasisAmount'
        /// </summary>
        [Test]
        public void TotalFeeBasisAmountTest()
        {
            // TODO unit test for the property 'TotalFeeBasisAmount'
        }
        /// <summary>
        /// Test the property 'TotalMarketplaceFee'
        /// </summary>
        [Test]
        public void TotalMarketplaceFeeTest()
        {
            // TODO unit test for the property 'TotalMarketplaceFee'
        }

    }

}
