/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing OrderRefund
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderRefundTests
    {
        // TODO uncomment below to declare an instance variable for OrderRefund
        //private OrderRefund instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderRefund
            //instance = new OrderRefund();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderRefund
        /// </summary>
        [Test]
        public void OrderRefundInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderRefund
            //Assert.IsInstanceOfType<OrderRefund> (instance, "variable 'instance' is a OrderRefund");
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'RefundDate'
        /// </summary>
        [Test]
        public void RefundDateTest()
        {
            // TODO unit test for the property 'RefundDate'
        }
        /// <summary>
        /// Test the property 'RefundId'
        /// </summary>
        [Test]
        public void RefundIdTest()
        {
            // TODO unit test for the property 'RefundId'
        }
        /// <summary>
        /// Test the property 'RefundReferenceId'
        /// </summary>
        [Test]
        public void RefundReferenceIdTest()
        {
            // TODO unit test for the property 'RefundReferenceId'
        }
        /// <summary>
        /// Test the property 'RefundStatus'
        /// </summary>
        [Test]
        public void RefundStatusTest()
        {
            // TODO unit test for the property 'RefundStatus'
        }

    }

}
