/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing PaymentDisputeOutcomeDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PaymentDisputeOutcomeDetailTests
    {
        // TODO uncomment below to declare an instance variable for PaymentDisputeOutcomeDetail
        //private PaymentDisputeOutcomeDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PaymentDisputeOutcomeDetail
            //instance = new PaymentDisputeOutcomeDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentDisputeOutcomeDetail
        /// </summary>
        [Test]
        public void PaymentDisputeOutcomeDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentDisputeOutcomeDetail
            //Assert.IsInstanceOfType<PaymentDisputeOutcomeDetail> (instance, "variable 'instance' is a PaymentDisputeOutcomeDetail");
        }


        /// <summary>
        /// Test the property 'Fees'
        /// </summary>
        [Test]
        public void FeesTest()
        {
            // TODO unit test for the property 'Fees'
        }
        /// <summary>
        /// Test the property 'ProtectedAmount'
        /// </summary>
        [Test]
        public void ProtectedAmountTest()
        {
            // TODO unit test for the property 'ProtectedAmount'
        }
        /// <summary>
        /// Test the property 'ProtectionStatus'
        /// </summary>
        [Test]
        public void ProtectionStatusTest()
        {
            // TODO unit test for the property 'ProtectionStatus'
        }
        /// <summary>
        /// Test the property 'ReasonForClosure'
        /// </summary>
        [Test]
        public void ReasonForClosureTest()
        {
            // TODO unit test for the property 'ReasonForClosure'
        }
        /// <summary>
        /// Test the property 'RecoupAmount'
        /// </summary>
        [Test]
        public void RecoupAmountTest()
        {
            // TODO unit test for the property 'RecoupAmount'
        }
        /// <summary>
        /// Test the property 'TotalFeeCredit'
        /// </summary>
        [Test]
        public void TotalFeeCreditTest()
        {
            // TODO unit test for the property 'TotalFeeCredit'
        }

    }

}
