/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing PaymentDisputeActivity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PaymentDisputeActivityTests
    {
        // TODO uncomment below to declare an instance variable for PaymentDisputeActivity
        //private PaymentDisputeActivity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PaymentDisputeActivity
            //instance = new PaymentDisputeActivity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentDisputeActivity
        /// </summary>
        [Test]
        public void PaymentDisputeActivityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentDisputeActivity
            //Assert.IsInstanceOfType<PaymentDisputeActivity> (instance, "variable 'instance' is a PaymentDisputeActivity");
        }


        /// <summary>
        /// Test the property 'ActivityDate'
        /// </summary>
        [Test]
        public void ActivityDateTest()
        {
            // TODO unit test for the property 'ActivityDate'
        }
        /// <summary>
        /// Test the property 'ActivityType'
        /// </summary>
        [Test]
        public void ActivityTypeTest()
        {
            // TODO unit test for the property 'ActivityType'
        }
        /// <summary>
        /// Test the property 'Actor'
        /// </summary>
        [Test]
        public void ActorTest()
        {
            // TODO unit test for the property 'Actor'
        }

    }

}
