/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing Payment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PaymentTests
    {
        // TODO uncomment below to declare an instance variable for Payment
        //private Payment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Payment
            //instance = new Payment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Payment
        /// </summary>
        [Test]
        public void PaymentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Payment
            //Assert.IsInstanceOfType<Payment> (instance, "variable 'instance' is a Payment");
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'PaymentDate'
        /// </summary>
        [Test]
        public void PaymentDateTest()
        {
            // TODO unit test for the property 'PaymentDate'
        }
        /// <summary>
        /// Test the property 'PaymentHolds'
        /// </summary>
        [Test]
        public void PaymentHoldsTest()
        {
            // TODO unit test for the property 'PaymentHolds'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Test]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'PaymentReferenceId'
        /// </summary>
        [Test]
        public void PaymentReferenceIdTest()
        {
            // TODO unit test for the property 'PaymentReferenceId'
        }
        /// <summary>
        /// Test the property 'PaymentStatus'
        /// </summary>
        [Test]
        public void PaymentStatusTest()
        {
            // TODO unit test for the property 'PaymentStatus'
        }

    }

}
