/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing Program
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProgramTests
    {
        // TODO uncomment below to declare an instance variable for Program
        //private Program instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Program
            //instance = new Program();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Program
        /// </summary>
        [Test]
        public void ProgramInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Program
            //Assert.IsInstanceOfType<Program> (instance, "variable 'instance' is a Program");
        }


        /// <summary>
        /// Test the property 'AuthenticityVerification'
        /// </summary>
        [Test]
        public void AuthenticityVerificationTest()
        {
            // TODO unit test for the property 'AuthenticityVerification'
        }
        /// <summary>
        /// Test the property 'EbayShipping'
        /// </summary>
        [Test]
        public void EbayShippingTest()
        {
            // TODO unit test for the property 'EbayShipping'
        }
        /// <summary>
        /// Test the property 'EbayVault'
        /// </summary>
        [Test]
        public void EbayVaultTest()
        {
            // TODO unit test for the property 'EbayVault'
        }
        /// <summary>
        /// Test the property 'EbayInternationalShipping'
        /// </summary>
        [Test]
        public void EbayInternationalShippingTest()
        {
            // TODO unit test for the property 'EbayInternationalShipping'
        }
        /// <summary>
        /// Test the property 'FulfillmentProgram'
        /// </summary>
        [Test]
        public void FulfillmentProgramTest()
        {
            // TODO unit test for the property 'FulfillmentProgram'
        }

    }

}
