/* 
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EBay.OAS3v1IV.Apis;
using EBay.OAS3v1IV.Models;
using EBay.OAS3v1IV.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EBay.OAS3v1IV.Test
{
    /// <summary>
    ///  Class for testing SellerActionsToRelease
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SellerActionsToReleaseTests
    {
        // TODO uncomment below to declare an instance variable for SellerActionsToRelease
        //private SellerActionsToRelease instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SellerActionsToRelease
            //instance = new SellerActionsToRelease();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SellerActionsToRelease
        /// </summary>
        [Test]
        public void SellerActionsToReleaseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SellerActionsToRelease
            //Assert.IsInstanceOfType<SellerActionsToRelease> (instance, "variable 'instance' is a SellerActionsToRelease");
        }


        /// <summary>
        /// Test the property 'SellerActionToRelease'
        /// </summary>
        [Test]
        public void SellerActionToReleaseTest()
        {
            // TODO unit test for the property 'SellerActionToRelease'
        }

    }

}
